"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FadeInOnScroll, TextReveal } from "@/components/ScrollEffects";

// ─── Data ────────────────────────────────────────────────────────────────────

const phases = [
    {
        id: "phase-1",
        label: "Phase 1",
        title: "Windows Fundamentals",
        color: "from-cyan-500/20 to-blue-500/10",
        borderColor: "border-cyan-500/30",
        accentColor: "text-cyan-400",
        dotColor: "bg-cyan-400",
        status: "active",
        projects: [
            {
                id: "P01",
                title: "Windows Authentication Investigation",
                status: "completed",
                severity: "medium",
                incidentId: "AUTH-001",
                summary:
                    "Investigated Windows authentication events in a SOC home lab environment. Analyzed failed and successful logon events using Splunk, Wazuh, and Sysmon. Built a complete authentication timeline and produced an incident report.",
                tools: ["Splunk Enterprise", "Wazuh", "Sysmon", "Event Viewer", "Kali Linux"],
                mitre: ["T1110 – Brute Force", "T1078 – Valid Accounts"],
                eventIds: ["4624", "4625", "4634", "4672", "4740"],
                outcome: "False Positive",
                outcomeColor: "text-cyber-green border-cyber-green/30 bg-green-500/10",
                tabs: {
                    overview: {
                        objectives: [
                            "Understand the Windows authentication process",
                            "Investigate failed and successful logon events",
                            "Analyze Windows Security Event Logs in Event Viewer",
                            "Learn how Splunk ingests Windows events via Universal Forwarder",
                            "Correlate authentication events into a complete timeline",
                            "Distinguish legitimate activity from suspicious authentication attempts",
                            "Build investigation documentation matching real SOC workflows",
                        ],
                        skills: [
                            "Windows Security Log Analysis",
                            "Authentication Investigation",
                            "Event Correlation",
                            "Timeline Reconstruction",
                            "Endpoint Monitoring",
                            "Splunk Fundamentals",
                            "SOC Documentation",
                            "Incident Analysis",
                        ],
                        taskStatus: [
                            { task: "Sysmon Installation", done: true },
                            { task: "Event Viewer Investigation", done: true },
                            { task: "Authentication Event Analysis", done: true },
                            { task: "Timeline Reconstruction", done: true },
                            { task: "Splunk Investigation", done: false, wip: true },
                            { task: "Wazuh Investigation", done: false, wip: false },
                            { task: "Detection Engineering", done: false, wip: false },
                            { task: "Incident Report", done: false, wip: false },
                            { task: "MITRE ATT&CK Mapping", done: false, wip: false },
                        ],
                    },
                    investigation: {
                        objective:
                            "Determine whether multiple failed logon events represent malicious activity or legitimate user behavior.",
                        evidence: [
                            { source: "Windows Security Log", items: ["Event ID 4625 – Failed Logon", "Event ID 4624 – Successful Logon", "Event ID 4672 – Special Privileges"] },
                            { source: "Sysmon", items: ["Installed for future investigations"] },
                            { source: "Splunk", items: ["Authentication events successfully ingested"] },
                        ],
                        findings: [
                            { id: "4625", desc: "Interactive Logon (Type 2) from 127.0.0.1 via svchost.exe — Failure: 'An error occurred during logon'" },
                            { id: "4624", desc: "Successful authentication immediately after three failed attempts" },
                            { id: "4672", desc: "Administrative privileges assigned — SeDebugPrivilege, SeBackupPrivilege, SeRestorePrivilege, SeTakeOwnershipPrivilege, SeImpersonatePrivilege" },
                        ],
                        conclusion:
                            "Authentication originated locally, performed interactively, and generated by legitimate Windows components. Timeline matches a user intentionally entering an incorrect password before a successful login. No indicators of malicious activity identified.",
                        classification: "False Positive",
                    },
                    timeline: [
                        { time: "07:09:29", id: "4625", desc: "Failed interactive logon", severity: "warn" },
                        { time: "07:09:32", id: "4625", desc: "Failed interactive logon", severity: "warn" },
                        { time: "07:09:33", id: "4625", desc: "Failed interactive logon", severity: "warn" },
                        { time: "07:09:36", id: "4624", desc: "Successful interactive logon", severity: "ok" },
                        { time: "07:09:36", id: "4672", desc: "Special privileges assigned", severity: "info" },
                        { time: "07:09:37+", id: "4624", desc: "Additional Windows logon sessions (normal)", severity: "info" },
                    ],
                    incidentReport: {
                        id: "AUTH-001",
                        status: "Closed",
                        severity: "Informational",
                        summary:
                            "Three failed authentication attempts followed by one successful authentication were investigated. Evidence indicates legitimate user activity.",
                        evidence: ["Event ID 4625 – Failed Logon (×3)", "Event ID 4624 – Successful Logon", "Event ID 4672 – Special Privileges Assigned"],
                        rootCause: "User intentionally entered incorrect password three times before successful authentication.",
                        recommendation: "No further action required. Continue monitoring authentication events.",
                    },
                },
            },
            {
                id: "P02",
                title: "Windows Process Creation Investigation",
                status: "planned",
                severity: "high",
                summary: "Investigate suspicious process creation events using Sysmon Event ID 1 and Splunk. Focus on LOLBins, PowerShell abuse, and command-line obfuscation patterns.",
                tools: ["Sysmon", "Splunk", "PowerShell"],
                mitre: ["T1059 – Command Scripting", "T1218 – LOLBins"],
                eventIds: ["4688", "1"],
                outcome: "Pending",
                outcomeColor: "text-white/30 border-white/10 bg-white/5",
                tabs: null,
            },
        ],
    },
    {
        id: "phase-2",
        label: "Phase 2",
        title: "SIEM Investigation",
        color: "from-purple-500/20 to-violet-500/10",
        borderColor: "border-purple-500/30",
        accentColor: "text-purple-400",
        dotColor: "bg-purple-400",
        status: "planned",
        projects: [
            {
                id: "P03",
                title: "Splunk Dashboards & Alerting",
                status: "planned",
                severity: "info",
                summary: "Build SOC-grade dashboards in Splunk with real-time authentication, process, and network alerts.",
                tools: ["Splunk"],
                mitre: [],
                eventIds: [],
                outcome: "Pending",
                outcomeColor: "text-white/30 border-white/10 bg-white/5",
                tabs: null,
            },
            {
                id: "P04",
                title: "Authentication Detection Engineering",
                status: "planned",
                severity: "high",
                summary: "Create Splunk detection rules for brute-force, pass-the-hash, and privilege escalation attacks.",
                tools: ["Splunk SPL", "Wazuh"],
                mitre: ["T1110", "T1078"],
                eventIds: ["4625", "4648"],
                outcome: "Pending",
                outcomeColor: "text-white/30 border-white/10 bg-white/5",
                tabs: null,
            },
        ],
    },
    {
        id: "phase-3",
        label: "Phase 3",
        title: "Threat Hunting",
        color: "from-red-500/20 to-rose-500/10",
        borderColor: "border-red-500/30",
        accentColor: "text-red-400",
        dotColor: "bg-red-400",
        status: "planned",
        projects: [
            {
                id: "P05",
                title: "LOLBins Detection",
                status: "planned",
                severity: "critical",
                summary: "Hunt for Living-off-the-Land binaries used for lateral movement and persistence in Windows environments.",
                tools: ["Sysmon", "Splunk", "MITRE ATT&CK"],
                mitre: ["T1218", "T1059.001"],
                eventIds: ["1", "4688"],
                outcome: "Pending",
                outcomeColor: "text-white/30 border-white/10 bg-white/5",
                tabs: null,
            },
        ],
    },
    {
        id: "phase-4",
        label: "Phase 4",
        title: "Detection Engineering",
        color: "from-amber-500/20 to-yellow-500/10",
        borderColor: "border-amber-500/30",
        accentColor: "text-amber-400",
        dotColor: "bg-amber-400",
        status: "planned",
        projects: [
            {
                id: "P06",
                title: "Sigma Rule Creation",
                status: "planned",
                severity: "high",
                summary: "Write Sigma rules for SIEM-agnostic threat detections, map them to MITRE ATT&CK, and convert to Splunk SPL and Wazuh rule formats.",
                tools: ["Sigma", "Splunk", "Wazuh"],
                mitre: ["T1059", "T1110", "T1078"],
                eventIds: [],
                outcome: "Pending",
                outcomeColor: "text-white/30 border-white/10 bg-white/5",
                tabs: null,
            },
        ],
    },
    {
        id: "phase-5",
        label: "Phase 5",
        title: "Incident Response",
        color: "from-green-500/20 to-emerald-500/10",
        borderColor: "border-green-500/30",
        accentColor: "text-green-400",
        dotColor: "bg-green-400",
        status: "planned",
        projects: [
            {
                id: "P07",
                title: "Full IR Simulation",
                status: "planned",
                severity: "critical",
                summary: "Simulate an end-to-end incident response lifecycle: triage, investigation, containment, eradication, and recovery on a compromised Windows endpoint.",
                tools: ["Splunk", "Wazuh", "Kali Linux", "Sysmon"],
                mitre: ["T1059", "T1110", "T1218"],
                eventIds: [],
                outcome: "Pending",
                outcomeColor: "text-white/30 border-white/10 bg-white/5",
                tabs: null,
            },
        ],
    },
];

// ─── Types ────────────────────────────────────────────────────────────────────

type TabKey = "overview" | "investigation" | "timeline" | "report";

interface TaskItem {
    task: string;
    done: boolean;
    wip?: boolean;
}

interface TimelineEvent {
    time: string;
    id: string;
    desc: string;
    severity: string;
}

interface EvidenceGroup {
    source: string;
    items: string[];
}

interface Finding {
    id: string;
    desc: string;
}

interface OverviewData {
    objectives: string[];
    skills: string[];
    taskStatus: TaskItem[];
}

interface InvestigationData {
    objective: string;
    evidence: EvidenceGroup[];
    findings: Finding[];
    conclusion: string;
    classification: string;
}

interface IncidentReportData {
    id: string;
    status: string;
    severity: string;
    summary: string;
    evidence: string[];
    rootCause: string;
    recommendation: string;
}

interface ProjectTabs {
    overview: OverviewData;
    investigation: InvestigationData;
    timeline: TimelineEvent[];
    incidentReport: IncidentReportData;
}

interface Project {
    id: string;
    title: string;
    status: string;
    severity: string;
    summary: string;
    tools: string[];
    mitre: string[];
    eventIds: string[];
    outcome: string;
    outcomeColor: string;
    tabs: ProjectTabs | null;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

const statusMap: Record<string, { dot: string; bg: string; text: string; label: string }> = {
    completed: { dot: "bg-cyber-green", bg: "bg-white/5", text: "text-white/70", label: "Completed" },
    "in-progress": { dot: "bg-yellow-400 animate-pulse", bg: "bg-white/5", text: "text-white/60", label: "In Progress" },
    planned: { dot: "bg-white/20", bg: "bg-white/5", text: "text-white/30", label: "Planned" },
    active: { dot: "bg-cyber-green animate-pulse", bg: "bg-white/5", text: "text-white/70", label: "Active" },
};

const severityMap: Record<string, string> = {
    critical: "text-white/65 border-white/20",
    high: "text-white/60 border-white/15",
    medium: "text-white/55 border-white/12",
    info: "text-white/45 border-white/10",
};

const timelineColors: Record<string, string> = {
    warn: "bg-yellow-400/70 shadow-yellow-400/20",
    ok: "bg-cyber-green shadow-cyber-green/20",
    info: "bg-white/40 shadow-white/10",
};

// ─── Detail Panel ────────────────────────────────────────────────────────────

function ProjectDetailPanel({ project }: { project: Project }) {
    const [tab, setTab] = useState<TabKey>("overview");

    if (!project.tabs) return null;
    const { overview, investigation, timeline, incidentReport } = project.tabs;

    const tabs: { id: TabKey; label: string }[] = [
        { id: "overview", label: "Overview" },
        { id: "investigation", label: "Investigation" },
        { id: "timeline", label: "Timeline" },
        { id: "report", label: "Report" },
    ];

    return (
        <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 8 }}
            transition={{ duration: 0.3 }}
            className="mt-4 glass-card border border-cyan-500/15 overflow-hidden"
        >
            {/* Tab bar */}
            <div className="flex gap-1 p-4 pb-0 border-b border-white/5 flex-wrap">
                {tabs.map((t) => (
                    <button
                        key={t.id}
                        onClick={() => setTab(t.id)}
                        className={`px-4 py-2 text-xs font-mono rounded-t-lg transition-all duration-200 ${
                            tab === t.id
                                ? "bg-white/10 text-white border-t border-l border-r border-white/10"
                                : "text-white/30 hover:text-white/60"
                        }`}
                    >
                        {t.label}
                    </button>
                ))}
            </div>

            <div className="p-5 text-sm">
                {/* OVERVIEW */}
                {tab === "overview" && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <h4 className="text-xs font-mono text-white/30 uppercase tracking-widest mb-3">Objectives</h4>
                            <ul className="space-y-2">
                                {overview.objectives.map((o, i) => (
                                    <li key={i} className="flex items-start gap-2 text-white/55 text-xs leading-relaxed">
                                        <span className="text-white/30 mt-0.5 flex-shrink-0">›</span>
                                        {o}
                                    </li>
                                ))}
                            </ul>
                        </div>
                        <div className="space-y-5">
                            <div>
                                <h4 className="text-xs font-mono text-white/30 uppercase tracking-widest mb-3">Task Status</h4>
                                <div className="space-y-1.5">
                                    {overview.taskStatus.map((t, i) => (
                                        <div key={i} className="flex items-center gap-2.5">
                                            <span className={`text-xs font-mono flex-shrink-0 ${t.done ? "text-cyber-green" : t.wip ? "text-white/50" : "text-white/20"}`}>
                                                {t.done ? "✓" : t.wip ? "—" : "○"}
                                            </span>
                                            <span className={`text-xs ${t.done ? "text-white/70" : t.wip ? "text-white/50" : "text-white/25"}`}>
                                                {t.task}
                                            </span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                            <div>
                                <h4 className="text-xs font-mono text-white/30 uppercase tracking-widest mb-3">Skills Demonstrated</h4>
                                <div className="flex flex-wrap gap-1.5">
                                    {overview.skills.map((s) => (
                                        <span key={s} className="px-2 py-0.5 rounded text-[10px] font-mono bg-white/5 border border-white/10 text-white/50">
                                            {s}
                                        </span>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>
                )}

                {/* INVESTIGATION */}
                {tab === "investigation" && (
                    <div className="space-y-5">
                        <div className="glass border border-white/5 rounded-xl p-4">
                            <p className="text-xs font-mono text-white/30 uppercase tracking-widest mb-1">Objective</p>
                            <p className="text-white/70 text-xs leading-relaxed">{investigation.objective}</p>
                        </div>
                        <div>
                            <p className="text-xs font-mono text-white/30 uppercase tracking-widest mb-3">Evidence Collected</p>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                                {investigation.evidence.map((e) => (
                                    <div key={e.source} className="glass-card p-3 border border-white/5">
                                        <p className="text-xs font-mono text-white/50 mb-2">{e.source}</p>
                                        <ul className="space-y-1">
                                            {e.items.map((item, i) => (
                                                <li key={i} className="text-[11px] text-white/50">• {item}</li>
                                            ))}
                                        </ul>
                                    </div>
                                ))}
                            </div>
                        </div>
                        <div>
                            <p className="text-xs font-mono text-white/30 uppercase tracking-widest mb-3">Key Findings</p>
                            <div className="space-y-2">
                                {investigation.findings.map((f) => (
                                    <div key={f.id} className="flex gap-3 items-start glass border border-white/5 rounded-lg p-3">
                                        <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-white/5 border border-white/10 text-white/55 flex-shrink-0 mt-0.5">
                                            {f.id}
                                        </span>
                                        <p className="text-xs text-white/55 leading-relaxed">{f.desc}</p>
                                    </div>
                                ))}
                            </div>
                        </div>
                        <div className="glass border border-white/8 rounded-xl p-4 bg-white/3">
                            <p className="text-xs font-mono text-white/40 mb-1">Classification: {investigation.classification}</p>
                            <p className="text-xs text-white/60 leading-relaxed">{investigation.conclusion}</p>
                        </div>
                    </div>
                )}

                {/* TIMELINE */}
                {tab === "timeline" && (
                    <div>
                        <p className="text-xs font-mono text-white/30 uppercase tracking-widest mb-4">Authentication Event Timeline</p>
                        <div className="relative pl-4">
                            <div className="absolute left-4 top-0 bottom-0 w-px bg-gradient-to-b from-white/20 via-white/8 to-transparent" />
                            <div className="space-y-3">
                                {timeline.map((evt, i) => (
                                    <motion.div
                                        key={i}
                                        initial={{ opacity: 0, x: -10 }}
                                        animate={{ opacity: 1, x: 0 }}
                                        transition={{ delay: i * 0.06 }}
                                        className="relative pl-6 flex items-start gap-3"
                                    >
                                        <div
                                            className={`absolute left-0 top-1.5 w-2.5 h-2.5 rounded-full shadow-lg -translate-x-[5px] flex-shrink-0 ${timelineColors[evt.severity] ?? "bg-white/30"}`}
                                        />
                                        <div className="flex flex-col sm:flex-row sm:items-center gap-1 sm:gap-3 flex-1">
                                            <span className="text-[11px] font-mono text-white/30 min-w-[70px] flex-shrink-0">{evt.time}</span>
                                            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-white/5 border border-white/8 text-white/50 flex-shrink-0">
                                                {evt.id}
                                            </span>
                                            <span className="text-xs text-white/60">{evt.desc}</span>
                                        </div>
                                    </motion.div>
                                ))}
                            </div>
                        </div>
                        <div className="mt-5 p-3 glass border border-white/5 rounded-xl">
                            <p className="text-xs text-white/40 leading-relaxed">
                                <span className="text-white/60 font-mono">Analysis: </span>
                                Three consecutive failed password attempts followed by a successful interactive logon and administrative privilege assignment.
                                No abnormal sequence observed — confirmed user-generated activity.
                            </p>
                        </div>
                    </div>
                )}

                {/* INCIDENT REPORT */}
                {tab === "report" && (
                    <div className="space-y-4">
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                            {[
                                { label: "Incident ID", value: incidentReport.id },
                                { label: "Status", value: incidentReport.status },
                                { label: "Severity", value: incidentReport.severity },
                                { label: "Classification", value: "False Positive" },
                            ].map((f) => (
                                <div key={f.label} className="glass-card p-3 border border-white/5">
                                    <p className="text-[10px] font-mono text-white/30 mb-1">{f.label}</p>
                                    <p className="text-sm font-mono font-bold text-white/80">{f.value}</p>
                                </div>
                            ))}
                        </div>
                        <div className="glass-card p-4 border border-white/5 space-y-3">
                            <div>
                                <p className="text-xs font-mono text-white/30 uppercase tracking-widest mb-1">Summary</p>
                                <p className="text-xs text-white/60 leading-relaxed">{incidentReport.summary}</p>
                            </div>
                            <div>
                                <p className="text-xs font-mono text-white/30 uppercase tracking-widest mb-2">Evidence</p>
                                {incidentReport.evidence.map((e, i) => (
                                    <div key={i} className="flex items-center gap-2 mb-1">
                                        <span className="text-white/30 text-xs">›</span>
                                        <span className="text-xs text-white/50">{e}</span>
                                    </div>
                                ))}
                            </div>
                            <div>
                                <p className="text-xs font-mono text-white/30 uppercase tracking-widest mb-1">Root Cause</p>
                                <p className="text-xs text-white/60 leading-relaxed">{incidentReport.rootCause}</p>
                            </div>
                            <div>
                                <p className="text-xs font-mono text-white/30 uppercase tracking-widest mb-1">Recommendation</p>
                                <p className="text-xs text-white/60 leading-relaxed">{incidentReport.recommendation}</p>
                            </div>
                        </div>
                    </div>
                )}
            </div>
        </motion.div>
    );
}

// ─── Project Card ─────────────────────────────────────────────────────────────

function ProjectCard({
    project,
    phaseBorderColor,
}: {
    project: Project;
    phaseAccent: string;
    phaseBorderColor: string;
}) {
    const [expanded, setExpanded] = useState(false);
    const s = statusMap[project.status];
    const sev = severityMap[project.severity] ?? severityMap.info;
    const hasDetails = !!project.tabs;

    return (
        <div>
            <motion.div
                whileHover={!expanded ? { x: 4 } : {}}
                transition={{ duration: 0.25 }}
                className={`glass-card-hover p-5 border ${expanded ? phaseBorderColor : "border-white/8"} transition-colors duration-300`}
            >
                <div className="flex flex-col md:flex-row md:items-start gap-3">
                    {/* Status dot + ID */}
                    <div className="flex items-center gap-2.5 min-w-[130px]">
                        <div className={`w-2 h-2 rounded-full flex-shrink-0 ${s.dot}`} />
                        <div>
                            <p className="text-[10px] font-mono text-white/25">{project.id}</p>
                            <span className={`text-xs font-mono px-2 py-0.5 rounded-full ${s.bg} ${s.text}`}>{s.label}</span>
                        </div>
                    </div>

                    {/* Content */}
                    <div className="flex-1 min-w-0">
                        <div className="flex items-start justify-between gap-2 mb-2 flex-wrap">
                            <h4 className="font-heading font-bold text-white/90 text-sm md:text-base">{project.title}</h4>
                            <span className={`text-[10px] font-mono px-2 py-0.5 rounded border flex-shrink-0 ${sev}`}>
                                {project.severity.toUpperCase()}
                            </span>
                        </div>

                        <p className="text-xs text-white/50 leading-relaxed mb-3">{project.summary}</p>

                        <div className="flex flex-wrap gap-4 text-xs font-mono mb-3">
                            {project.eventIds.length > 0 && (
                                <span className="text-white/30">
                                    Events: <span className="text-white/55">{project.eventIds.join(", ")}</span>
                                </span>
                            )}
                            <span className="text-white/30">
                                Tools: <span className="text-white/55">{project.tools.join(", ")}</span>
                            </span>
                        </div>

                        {/* MITRE tags + outcome */}
                        <div className="flex flex-wrap items-center gap-2">
                            {project.mitre.map((m) => (
                                <span key={m} className="text-[10px] font-mono px-2 py-0.5 rounded bg-white/5 border border-white/8 text-white/35">
                                    {m}
                                </span>
                            ))}
                            {project.outcome !== "Pending" && (
                                <span className={`text-[10px] font-mono px-2 py-0.5 rounded border ${project.outcomeColor}`}>
                                    {project.outcome}
                                </span>
                            )}
                        </div>
                    </div>

                    {/* Expand button */}
                    {hasDetails && (
                        <button
                            onClick={() => setExpanded((v) => !v)}
                            className={`flex-shrink-0 self-start px-4 py-2 rounded-lg text-xs font-mono transition-all duration-300 ${
                                expanded
                                    ? "bg-white/10 border border-white/20 text-white/80"
                                    : "glass border border-white/10 text-white/40 hover:text-white/70"
                            }`}
                        >
                            {expanded ? "Close" : "Details"}
                        </button>
                    )}
                </div>
            </motion.div>

            <AnimatePresence>
                {expanded && hasDetails && <ProjectDetailPanel project={project} />}
            </AnimatePresence>
        </div>
    );
}

// ─── Main Section ─────────────────────────────────────────────────────────────

export default function SOCProjects() {
    const [activePhase, setActivePhase] = useState("phase-1");
    const currentPhase = phases.find((p) => p.id === activePhase)!;

    const allProjects = phases.flatMap((p) => p.projects);
    const completedCount = allProjects.filter((p) => p.status === "completed").length;

    return (
        <section id="soc-projects" className="relative py-24 md:py-32 px-6 overflow-hidden">
            {/* Ambient glows */}
            <div className="absolute top-1/3 right-1/4 w-[500px] h-[500px] bg-cyan-600/4 rounded-full blur-[160px]" />
            <div className="absolute bottom-1/4 left-1/3 w-[400px] h-[400px] bg-purple-600/4 rounded-full blur-[130px]" />

            <div className="max-w-6xl mx-auto relative">
                {/* Section header */}
                <FadeInOnScroll direction="up">
                    <div className="text-center mb-14">
                        <p className="text-sm font-mono text-white/30 tracking-widest uppercase mb-3">
                            [ SOC Analyst Portfolio ]
                        </p>
                        <h2 className="text-4xl md:text-5xl font-heading font-black tracking-tight">
                            <TextReveal text="SOC Projects" className="gradient-text" />
                        </h2>
                        <p className="mt-4 text-white/40 max-w-lg mx-auto">
                            Hands-on cybersecurity investigations built inside a personal SOC home lab —
                            from Windows event analysis to threat hunting and detection engineering.
                        </p>
                    </div>
                </FadeInOnScroll>

                {/* Stats strip */}
                <FadeInOnScroll direction="up" delay={0.05}>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-10">
                        {[
                            { label: "Projects Completed", value: completedCount },
                            { label: "Total Projects", value: allProjects.length },
                            { label: "Phases", value: phases.length },
                            { label: "Tools Used", value: "6+" },
                        ].map((stat) => (
                            <div key={stat.label} className="glass-card p-4 border border-white/5 text-center">
                                <p className="text-2xl font-heading font-black text-white/90">{stat.value}</p>
                                <p className="text-[10px] font-mono text-white/30 mt-1">{stat.label}</p>
                            </div>
                        ))}
                    </div>
                </FadeInOnScroll>

                {/* Phase selector tabs */}
                <FadeInOnScroll direction="up" delay={0.08}>
                    <div className="flex flex-wrap gap-2 mb-8">
                        {phases.map((phase) => {
                            const s = statusMap[phase.status];
                            const isActive = activePhase === phase.id;
                            return (
                                <button
                                    key={phase.id}
                                    onClick={() => setActivePhase(phase.id)}
                                    className={`px-4 py-2.5 rounded-xl text-xs font-mono font-medium transition-all duration-300 flex items-center gap-2 ${
                                        isActive
                                            ? `bg-white/8 border ${phase.borderColor} text-white/90`
                                            : "glass border border-white/8 text-white/35 hover:text-white/60"
                                    }`}
                                >
                                    <div className={`w-1.5 h-1.5 rounded-full ${isActive ? phase.dotColor : "bg-white/20"}`} />
                                    <span>{phase.label}</span>
                                    <span className="hidden sm:inline text-white/40">— {phase.title}</span>
                                    <span className={`text-[9px] px-1.5 py-0.5 rounded-full ${s.bg} ${s.text}`}>{s.label}</span>
                                </button>
                            );
                        })}
                    </div>
                </FadeInOnScroll>

                {/* Phase content panel */}
                <AnimatePresence mode="wait">
                    <motion.div
                        key={activePhase}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        exit={{ opacity: 0, y: -6 }}
                        transition={{ duration: 0.3 }}
                    >
                        {/* Phase header */}
                        <div className={`glass-card p-5 border ${currentPhase.borderColor} mb-6 flex items-center gap-4`}>
                            <div
                                className={`w-3 h-3 rounded-full ${currentPhase.dotColor} ${
                                    currentPhase.status === "active" ? "animate-pulse" : ""
                                }`}
                            />
                            <div>
                                <p className="text-xs font-mono text-white/30 uppercase tracking-widest">
                                    {currentPhase.label}
                                </p>
                                <h3 className="font-heading font-bold text-white/90">{currentPhase.title}</h3>
                            </div>
                            <span
                                className={`ml-auto text-xs font-mono px-2 py-0.5 rounded-full ${statusMap[currentPhase.status].bg} ${statusMap[currentPhase.status].text}`}
                            >
                                {statusMap[currentPhase.status].label}
                            </span>
                        </div>

                        {/* Project cards */}
                        <div className="flex flex-col gap-4">
                            {currentPhase.projects.map((project, i) => (
                                <FadeInOnScroll key={project.id} direction="up" delay={i * 0.07}>
                                    <ProjectCard
                                        project={project as Project}
                                        phaseAccent={currentPhase.accentColor}
                                        phaseBorderColor={currentPhase.borderColor}
                                    />
                                </FadeInOnScroll>
                            ))}
                        </div>
                    </motion.div>
                </AnimatePresence>

                {/* Footer status bar */}
                <FadeInOnScroll direction="up" delay={0.25}>
                    <div className="mt-10 glass-card p-5 border border-white/5 flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
                        <div className="flex items-center gap-3">
                            <div className="w-2 h-2 rounded-full bg-cyber-green animate-pulse" />
                            <span className="text-sm font-mono text-white/50">SOC Learning Journey — Active</span>
                        </div>
                        <div className="flex flex-wrap gap-4 text-xs font-mono text-white/25">
                            <span>Platform: Windows 11 + VirtualBox</span>
                            <span>SIEM: Splunk + Wazuh</span>
                            <span>Framework: MITRE ATT&amp;CK</span>
                            <span>
                                Progress:{" "}
                                <span className="text-white/55">
                                    {completedCount}/{allProjects.length} projects
                                </span>
                            </span>
                        </div>
                    </div>
                </FadeInOnScroll>
            </div>
        </section>
    );
}
